#! /bin/sh
# /etc/init.d/blynkserver

### BEGIN INIT INFO
# Provides:          blynkserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Blynk Server Service
# Description:       Start and stop the Blynk Server Service.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Blynk Server"
    # run application you want to start
    java -jar /opt/blynkserver/server-0.41.6-java8.jar -serverConfig /opt/blynkserver/blynk_server.properties &
    ;;
  stop)
    echo "Stopping Blynk Server"
    # kill application you want to stop
    PID = ps -ef | grep 'blynk' | grep -v grep | awk '{print $2}' | tail -n 1
    kill $PID
    ;;
  *)
    echo "Usage: /etc/init.d/blynkserver {start|stop}"
    exit 1
    ;;
esac

exit 0