#! /bin/sh
# /etc/init.d/smokey_service

### BEGIN INIT INFO
# Provides:          smokey_service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Smokey Service
# Description:       Start and stop the Smokey Service.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Smokey Service"
    # run application you want to start
    python3 /home/pi/SmokeyMcSmokerson/Software/Controller/smokey_mc_smokerson/smokey_mc_smokerson.py &
    ;;
  stop)
    echo "Stopping Smokey Service"
    # kill application you want to stop
	# For some reason, some OS'es act differently and you might need to remove the | tail -n 1
    kill $(ps -ef | grep 'smokey_mc_smokerson.py' | grep -v grep | awk '{print $2}' | tail -n 1)
    ;;
  *)
    echo "Usage: /etc/init.d/smokey_service {start|stop}"
    exit 1
    ;;
esac

exit 0